services:
  book_catalog:
    build: ./book_catalog
    image: akashgajjala10/book_catalog:v1
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://reddy_sit722_part2_uc59_user:KNSBcPt8xOSQdGVGLtS1QlaKQBHlmRGe@dpg-crkbmvjv2p9s73b4pr1g-a.oregon-postgres.render.com/reddy_sit722_part2_uc59
---
    depends_on:
      - postgres

  inventory_management:
    build: ./inventory_management
    image: akashgajjala10/inventory_management:v1
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://reddy_sit722_part2_uc59_user:KNSBcPt8xOSQdGVGLtS1QlaKQBHlmRGe@dpg-crkbmvjv2p9s73b4pr1g-a.oregon-postgres.render.com/reddy_sit722_part2_uc59
---
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: reddy_sit722_part2_uc59_user
      POSTGRES_PASSWORD: KNSBcPt8xOSQdGVGLtS1QlaKQBHlmRGe
      POSTGRES_DB: eddy_sit722_part2_uc59
    ports:
      - "5433:5432"
